version: '3'
services:
  minio1:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    ports:
      - 9001:9000
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server https://minio1:9000/data https://minio2:9000/data https://minio3:9000/data https://minio4:9000/data
    volumes:
      - /tmp/certs/minio1:/root/.minio/certs
  minio2:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server https://minio1:9000/data https://minio2:9000/data https://minio3:9000/data https://minio4:9000/data
    volumes:
      - /tmp/certs/minio2:/root/.minio/certs
  minio3:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server https://minio1:9000/data https://minio2:9000/data https://minio3:9000/data https://minio4:9000/data
    volumes:
      - /tmp/certs/minio3:/root/.minio/certs
  minio4:
    image: minio/minio:RELEASE.2020-09-23T19-18-30Z
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server https://minio1:9000/data https://minio2:9000/data https://minio3:9000/data https://minio4:9000/data
    volumes:
      - /tmp/certs/minio4:/root/.minio/certs
